FROM php:8.1.0-cli

RUN apt-get update && apt-get upgrade -y \
    git curl wget \
    libpq-dev libonig-dev libmemcached-dev libmcrypt-dev libxml2-dev \
    libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev libicu-dev g++ libzip-dev zip \
    && apt-get install apt-utils -y \
    && apt-get install git zip vim libzip-dev libgmp-dev libffi-dev libssl-dev cron -y \
    && pecl install xdebug \
    && pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-install -j$(nproc) opcache mbstring pdo pdo_pgsql pgsql sockets zip gmp pcntl bcmath ffi pcntl shmop ftp \
    && docker-php-source delete \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-enable redis \
    && apt-get autoremove --purge -y && apt-get autoclean -y && apt-get clean -y

# Установим Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

# Установим Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=Composer
RUN composer require doctrine maker

EXPOSE 9000

CMD symfony serve --allow-http --no-tls --port=9000